version: "3.8"

services:
  landscape:
    build:
      context: .
      args:
        - REACT_APP_PROTO_JSON_HOST=https://openapi.acme.dev/
        - REACT_APP_PROTO_JSON_PATH=spec/json/protos.json
        - REACT_APP_GITHUB_API_PRJ_URL=https://api.github.com/repos/XXXXXXXXX/diagramm_store/
        - REACT_APP_GITLAB_API_PRJ_URL=https://gitlab.acme.dev/api/v4/projects/NNNN/
    ports:
      - "5000:5000"

  excalidraw:
    image: excalidraw/excalidraw:latest
    ports:
      - 5000:80

  room:
    image: excalidraw/excalidraw-room
    ports:
      - 3003:80

volumes:
  notused:
